ipaddr: 192.168.56.10
spring:
  datasource:
    url: jdbc:mysql://${ipaddr}:3306/cloudtemp_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    com.macro.mall: debug